apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: {{ .Value.deployment.replicas }}
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
#pod defination    
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:{{ .Values.deployment.imageVersion }}




# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: mysql
#   namespace: expense
#   # these labels are deployment related labels
#   labels:
#     component: mysql
#     project: expense
#     tier: db
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       component: mysql
#       project: expense
#       tier: db
#   # pod definition
#   template:
#     metadata:
#       labels:
#         component: mysql
#         project: expense
#         tier: db
#     spec:
#       containers:
#       - name: mysql
#         image: joindevops/mysql:v1.0


#kubectl get pods -n expense
#sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
#sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens
#kubens <namespace name>
#helm install mysql .
#